### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [nlmixr2/rxode2#324] opened 2022-10-10 09:07 UTC
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that your package somehow includes references to ggplot2 code from when it was build, which causes the check to emit the "Import not declared from..." error. Please see https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/ for some more info about why this can cause issues.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by mattfidler** [comment] 2022-10-10 09:43
Hi @thomasp85 

We follow all the recommendations on your blog post.  I am unsure why you are seeing this error.  I would not want to run into this in the future, but I am unclear what the cause is at this point.

When we tested against the win-builder ggplot2 3.4, we saw a `ggproto` change where it requires `linewidth` instead of `size`.  This was taken care of already.  I will also test with the release candidate.

**Comment by mattfidler** [comment] 2022-10-10 09:47
Hm.  I just noticed that I am using `compareVersion(as.character(packageVersion("ggplot2"))` to `3.4.0` for some fixes.  I am changing it to `3.3.6.9000`.

**Comment by mattfidler** [comment] 2022-10-10 09:50
@thomasp85  that is very kind.

**Comment by mattfidler** [comment] 2022-10-10 09:51
Rerunning the test on the release candidate.  Whatever it is could have already been fixed in the development version.

**Comment by thomasp85** [comment] 2022-10-10 09:56
Will test with the GitHub version of rxode2 to confirm. We are only running revdepchecks on the CRAN version of packages

**Comment by mattfidler** [comment] 2022-10-10 10:00
This repository is in a bit of a hard to test state.  CRAN has asked us to split into separate packages to reduce compile time.  I know you are busy, I will simply confirm that the release candidate is working on my development machine.

**Comment by thomasp85** [comment] 2022-10-10 10:01
gotcha - if you see no issues when checking with the RC version I'll assume all is good

**Comment by mattfidler** [comment] 2022-10-10 10:18
Nothing substantial with `::test()`; file differences in plots but not visual differences (at least to my eye).  Will do `::check()` now

**Comment by mattfidler** [comment] 2022-10-10 10:45
No problems from my end saying `Imports not declared from` with the `rc`.   I don't recall it ever saying that in my checks on cran win-builder either..

Only one question, should I have `compareVersion(as.character(packageVersion("ggplot2")), "3.3.6.9000")` or `compareVersion(as.character(packageVersion("ggplot2")), "3.4.0")` or does it matter?

**Comment by mattfidler** [comment] 2022-10-19 16:04
Hi @thomasp85 

I believe these are fixed for `ggplot2`  `3.4`.

'rxode2' hit CRAN today.

**Closed by mattfidler** 2022-10-19 16:04 UTC
