### ISSUE TITLE
Length of parameters in icov affects speed of rxSolve

### ISSUE THREAD

**Issue by danieleboaretti** [nlmixr2/rxode2#743] opened 2024-07-30 13:54 UTC
Hello,

I would like to report a note about the time taken by rxSolve whean dealing with iCov. It looks like that the number of parameters in iCov affects the time required for the solution of the system of ODE.

A minimal working and reproducible example is here. I use some functions from the collapse and magrittr function in the first definitions that are irrelevant for the benchmark. In both cases I am running the simulations with the same parameters as you can see below, it is just a matter of passing them in the "right" way.

```R
library(collapse)
library(rxode2)
library(magrittr)
nsub <- 100 # 100 sub-problems

mod1 <- rxode2({
    C2 = centr/V2
    C3 = peri/V3
    d/dt(depot) = -KA*depot
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3
    d/dt(peri) = Q*C2 - Q*C3
    d/dt(eff) = Kin - Kout*(1-C2/(EC50+C2))*eff
    eff(0) = 1
})


ev <- et() %>%
    et(amt=10000, addl=9,ii=12) %>%
    et(time=120, amt=20000, addl=4, ii=24) %>%
    et(0:240) ## Add Sampling

  sampling_times_df <- data.frame(
    id = rep(1:nsub, each = length(seq(0,240))),
    time = rep(seq(0,240), nsub),
    evid = 0,
    cmt = "(obs)"
  )

  ev %<>% rowbind(sampling_times_df, fill = TRUE)

  ev %<>% roworder(id, time, evid)

sigma <- matrix(c(0.09,0.08,0.08,0.25),2,2) # IIV covariance matrix
mv <- rxRmvn(n=nsub, rep(0,2), sigma) # Sample from covariance matrix
CL <- 7*exp(mv[,1])
V2 <- 40*exp(mv[,2])
params.all <- cbind(KA=0.3, CL=CL, V2=V2, Q=10, V3=300,
                    Kin=0.2, Kout=0.2, EC50=8)
params_df <- as.data.frame(params.all)
runiCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =params_df, events=ev)
}

icovs <- params_df[c("CL", "V2")]
params_small_icovs <- params_df[c("KA", "Q", "V3", "Kin", "Kout", "EC50")]
run_small_iCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =icovs, params = params_small_icovs, events=ev)
}
library(microbenchmark)
bench <- microbenchmark(run_small_iCov(), runiCov())
print(bench)
```

The output is here:
```
Unit: milliseconds
             expr      min       lq     mean   median       uq      max neval
 run_small_iCov()  99.5465 153.8880 185.3077 175.3835 206.7476 505.7178   100
        runiCov() 201.1491 293.1483 364.3885 349.6531 428.4686 689.8253   100
```

I am expecting that the computational time would be the same not like the double hen passing all parameters as icov. I am wondering what is causing this noticeable difference.

This problem is more a test case, but it could be quite a drawback if one has to simulate many covariates and use the iCov argument with many parameters.. 

Thank you for your support.

Daniele

**Comment by mattfidler** [comment] 2024-08-01 01:31
Hi @danieleboaretti 

I cannot reproduce what you are getting with the latest `rxode2`;  Here is what I get

``` r
library(collapse)
#> Error in library(collapse): there is no package called 'collapse'
library(rxode2)
#> rxode2 2.1.3.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
library(magrittr)
nsub <- 100 # 100 sub-problems

mod1 <- rxode2({
  C2 = centr/V2
  C3 = peri/V3
  d/dt(depot) = -KA*depot
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3
  d/dt(peri) = Q*C2 - Q*C3
  d/dt(eff) = Kin - Kout*(1-C2/(EC50+C2))*eff
  eff(0) = 1
})


ev <- et() %>%
  et(amt=10000, addl=9,ii=12) %>%
  et(time=120, amt=20000, addl=4, ii=24) %>%
  et(0:240) ## Add Sampling

sampling_times_df <- data.frame(
  id = rep(1:nsub, each = length(seq(0,240))),
  time = rep(seq(0,240), nsub),
  evid = 0,
  cmt = "(obs)"
)

ev %<>% rowbind(sampling_times_df, fill = TRUE)
#> Error in rowbind(., sampling_times_df, fill = TRUE): could not find function "rowbind"

ev %<>% roworder(id, time, evid)
#> Error in roworder(., id, time, evid): could not find function "roworder"

sigma <- matrix(c(0.09,0.08,0.08,0.25),2,2) # IIV covariance matrix
mv <- rxRmvn(n=nsub, rep(0,2), sigma) # Sample from covariance matrix
CL <- 7*exp(mv[,1])
V2 <- 40*exp(mv[,2])
params.all <- cbind(KA=0.3, CL=CL, V2=V2, Q=10, V3=300,
                    Kin=0.2, Kout=0.2, EC50=8)
params_df <- as.data.frame(params.all)
runiCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =params_df, events=ev)
}

icovs <- params_df[c("CL", "V2")]
params_small_icovs <- params_df[c("KA", "Q", "V3", "Kin", "Kout", "EC50")]
run_small_iCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =icovs, params = params_small_icovs, events=ev)
}
library(microbenchmark)
bench <- microbenchmark(run_small_iCov(), runiCov())
#> Error in rxSolve.default(mod1, iCov = params_df, events = ev): to use 'iCov' you must have an id in your event table
print(bench)
#> Error in eval(expr, envir, enclos): object 'bench' not found
```

<sup>Created on 2024-07-31 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

That being said, the `iCov` is a simple convince parmeter that merges the `iCov` to the event table;  You can see the R code here:

https://github.com/nlmixr2/rxode2/blob/2d1e96a7ed5558018c1c503ed8776bce309890d6/R/rxsolve.R#L1644

If you have a better way or faster way to merge it outside of `rxode2` that would speed up the problem.

**Comment by mattfidler** [comment] 2024-08-01 01:35
I forgot the `collapse`  package.

I can reproduce it here:

``` r
library(collapse)
#> collapse 2.0.15, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
library(rxode2)
#> rxode2 2.1.3.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
library(magrittr)
nsub <- 100 # 100 sub-problems

mod1 <- rxode2({
  C2 = centr/V2
  C3 = peri/V3
  d/dt(depot) = -KA*depot
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3
  d/dt(peri) = Q*C2 - Q*C3
  d/dt(eff) = Kin - Kout*(1-C2/(EC50+C2))*eff
  eff(0) = 1
})


ev <- et() %>%
  et(amt=10000, addl=9,ii=12) %>%
  et(time=120, amt=20000, addl=4, ii=24) %>%
  et(0:240) ## Add Sampling

sampling_times_df <- data.frame(
  id = rep(1:nsub, each = length(seq(0,240))),
  time = rep(seq(0,240), nsub),
  evid = 0,
  cmt = "(obs)"
)

ev %<>% rowbind(sampling_times_df, fill = TRUE)

ev %<>% roworder(id, time, evid)

sigma <- matrix(c(0.09,0.08,0.08,0.25),2,2) # IIV covariance matrix
mv <- rxRmvn(n=nsub, rep(0,2), sigma) # Sample from covariance matrix
CL <- 7*exp(mv[,1])
V2 <- 40*exp(mv[,2])
params.all <- cbind(KA=0.3, CL=CL, V2=V2, Q=10, V3=300,
                    Kin=0.2, Kout=0.2, EC50=8)
params_df <- as.data.frame(params.all)
runiCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =params_df, events=ev)
}

icovs <- params_df[c("CL", "V2")]
params_small_icovs <- params_df[c("KA", "Q", "V3", "Kin", "Kout", "EC50")]
run_small_iCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =icovs, params = params_small_icovs, events=ev)
}
library(microbenchmark)
bench <- microbenchmark(run_small_iCov(), runiCov())
print(bench)
#> Unit: milliseconds
#>              expr      min        lq     mean    median       uq      max neval
#>  run_small_iCov()  78.1508  82.64216 101.5721  88.28421 107.5780 208.5788   100
#>         runiCov() 154.0985 164.94499 201.4507 189.08046 214.1042 322.6492   100

Rprof()
runiCov()
#> ── Solved rxode2 object ──
#> ── Parameters (x$params): ──
#> # A tibble: 1 × 0
#> ── Initial Conditions (x$inits): ──
#> depot centr  peri   eff 
#>     0     0     0     1 
#> ── First part of data (object): ──
#> # A tibble: 24,341 × 16
#>      id  time    C2    C3  depot centr  peri   eff    KA    CL    V2     Q    V3
#>   <int> <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1     1     0   0   0     10000     0     0   1      0.3  8.96  88.4    10   300
#> 2     1     0   0   0     10000     0     0   1      0.3  8.96  88.4    10   300
#> 3     1     1  26.3 0.472  7408. 2322.  142.  1.11   0.3  8.96  88.4    10   300
#> 4     1     1  26.3 0.472  7408. 2322.  142.  1.11   0.3  8.96  88.4    10   300
#> 5     1     2  40.7 1.58   5488. 3602.  474.  1.27   0.3  8.96  88.4    10   300
#> 6     1     2  40.7 1.58   5488. 3602.  474.  1.27   0.3  8.96  88.4    10   300
#> # ℹ 24,335 more rows
#> # ℹ 3 more variables: Kin <dbl>, Kout <dbl>, EC50 <dbl>
Rprof(NULL)
summaryRprof()
#> $by.self
#>                               self.time self.pct total.time total.pct
#> "rxSolveSEXP"                      0.34    60.71       0.34     60.71
#> "$.rxSolve"                        0.10    17.86       0.10     17.86
#> "lazyLoadDBfetch"                  0.04     7.14       0.04      7.14
#> "knit_print.data.frame"            0.02     3.57       0.22     39.29
#> "$"                                0.02     3.57       0.12     21.43
#> "class"                            0.02     3.57       0.02      3.57
#> "format.pillar_shaft_decimal"      0.02     3.57       0.02      3.57
#> 
#> $by.total
#>                               total.time total.pct self.time self.pct
#> "<Anonymous>"                       0.56    100.00      0.00     0.00
#> "base::do.call"                     0.56    100.00      0.00     0.00
#> "base::saveRDS"                     0.56    100.00      0.00     0.00
#> "base::tryCatch"                    0.56    100.00      0.00     0.00
#> "base::withCallingHandlers"         0.56    100.00      0.00     0.00
#> "block_exec"                        0.56    100.00      0.00     0.00
#> "call_block"                        0.56    100.00      0.00     0.00
#> "doTryCatch"                        0.56    100.00      0.00     0.00
#> "eng_r"                             0.56    100.00      0.00     0.00
#> "evaluate_call"                     0.56    100.00      0.00     0.00
#> "evaluate::evaluate"                0.56    100.00      0.00     0.00
#> "evaluate"                          0.56    100.00      0.00     0.00
#> "handle"                            0.56    100.00      0.00     0.00
#> "in_dir"                            0.56    100.00      0.00     0.00
#> "in_input_dir"                      0.56    100.00      0.00     0.00
#> "knitr::knit"                       0.56    100.00      0.00     0.00
#> "process_file"                      0.56    100.00      0.00     0.00
#> "process_group"                     0.56    100.00      0.00     0.00
#> "rmarkdown::render"                 0.56    100.00      0.00     0.00
#> "try"                               0.56    100.00      0.00     0.00
#> "tryCatch"                          0.56    100.00      0.00     0.00
#> "tryCatchList"                      0.56    100.00      0.00     0.00
#> "tryCatchOne"                       0.56    100.00      0.00     0.00
#> "withCallingHandlers"               0.56    100.00      0.00     0.00
#> "withVisible"                       0.56    100.00      0.00     0.00
#> "xfun:::handle_error"               0.56    100.00      0.00     0.00
#> "rxSolveSEXP"                       0.34     60.71      0.34    60.71
#> ".collectWarnings"                  0.34     60.71      0.00     0.00
#> "eval_with_user_handlers"           0.34     60.71      0.00     0.00
#> "eval"                              0.34     60.71      0.00     0.00
#> "runiCov"                           0.34     60.71      0.00     0.00
#> "rxSolve.default"                   0.34     60.71      0.00     0.00
#> "rxSolve"                           0.34     60.71      0.00     0.00
#> "suppressWarnings"                  0.34     60.71      0.00     0.00
#> "timing_fn"                         0.34     60.71      0.00     0.00
#> "knit_print.data.frame"             0.22     39.29      0.02     3.57
#> "fun"                               0.22     39.29      0.00     0.00
#> "knit_print"                        0.22     39.29      0.00     0.00
#> "value_fun"                         0.22     39.29      0.00     0.00
#> "context$df_print"                  0.20     35.71      0.00     0.00
#> "print.rxSolve"                     0.20     35.71      0.00     0.00
#> "$"                                 0.12     21.43      0.02     3.57
#> "$.rxSolve"                         0.10     17.86      0.10    17.86
#> "print"                             0.10     17.86      0.00     0.00
#> "format"                            0.08     14.29      0.00     0.00
#> "format_tbl"                        0.06     10.71      0.00     0.00
#> "format.tbl"                        0.06     10.71      0.00     0.00
#> "print_tbl"                         0.06     10.71      0.00     0.00
#> "print.tbl"                         0.06     10.71      0.00     0.00
#> "tbl_format_setup_dispatch"         0.06     10.71      0.00     0.00
#> "tbl_format_setup.tbl"              0.06     10.71      0.00     0.00
#> "tbl_format_setup"                  0.06     10.71      0.00     0.00
#> "writeLines"                        0.06     10.71      0.00     0.00
#> "lazyLoadDBfetch"                   0.04      7.14      0.04     7.14
#> "ctl_colonnade"                     0.04      7.14      0.00     0.00
#> "FUN"                               0.04      7.14      0.00     0.00
#> "NextMethod"                        0.04      7.14      0.00     0.00
#> "print.rxSolveParams"               0.04      7.14      0.00     0.00
#> "class"                             0.02      3.57      0.02     3.57
#> "format.pillar_shaft_decimal"       0.02      3.57      0.02     3.57
#> "...elt"                            0.02      3.57      0.00     0.00
#> "add_handler"                       0.02      3.57      0.00     0.00
#> "addCenvFrame"                      0.02      3.57      0.00     0.00
#> "addCenvVars"                       0.02      3.57      0.00     0.00
#> "as.vector"                         0.02      3.57      0.00     0.00
#> "cat"                               0.02      3.57      0.00     0.00
#> "cli::cli_format_method"            0.02      3.57      0.00     0.00
#> "cmpfun"                            0.02      3.57      0.00     0.00
#> "compiler:::tryCmpfun"              0.02      3.57      0.00     0.00
#> "ctl_new_pillar.tbl"                0.02      3.57      0.00     0.00
#> "ctl_new_pillar"                    0.02      3.57      0.00     0.00
#> "ctl_new_rowid_pillar.tbl"          0.02      3.57      0.00     0.00
#> "ctl_new_rowid_pillar"              0.02      3.57      0.00     0.00
#> "defer"                             0.02      3.57      0.00     0.00
#> "do_emit_focus_pillars"             0.02      3.57      0.00     0.00
#> "do_emit_pillars"                   0.02      3.57      0.00     0.00
#> "do_emit_tiers"                     0.02      3.57      0.00     0.00
#> "emit_pillars"                      0.02      3.57      0.00     0.00
#> "exit_frame"                        0.02      3.57      0.00     0.00
#> "format.boundParams"                0.02      3.57      0.00     0.00
#> "frame_loc"                         0.02      3.57      0.00     0.00
#> "funEnv"                            0.02      3.57      0.00     0.00
#> "is"                                0.02      3.57      0.00     0.00
#> "knitr::asis_output"                0.02      3.57      0.00     0.00
#> "lapply"                            0.02      3.57      0.00     0.00
#> "loadNamespace"                     0.02      3.57      0.00     0.00
#> "make.functionContext"              0.02      3.57      0.00     0.00
#> "map"                               0.02      3.57      0.00     0.00
#> "methods::getFunction"              0.02      3.57      0.00     0.00
#> "paged_table_html"                  0.02      3.57      0.00     0.00
#> "paste"                             0.02      3.57      0.00     0.00
#> "pillar_format_parts_2"             0.02      3.57      0.00     0.00
#> "pillar_from_shaft"                 0.02      3.57      0.00     0.00
#> "pillar"                            0.02      3.57      0.00     0.00
#> "print.boundParams"                 0.02      3.57      0.00     0.00
#> "print.paged_df"                    0.02      3.57      0.00     0.00
#> "start_app"                         0.02      3.57      0.00     0.00
#> "structure"                         0.02      3.57      0.00     0.00
#> "union"                             0.02      3.57      0.00     0.00
#> "utils::capture.output"             0.02      3.57      0.00     0.00
#> "vapply"                            0.02      3.57      0.00     0.00
#> 
#> $sample.interval
#> [1] 0.02
#> 
#> $sampling.time
#> [1] 0.56
```

<sup>Created on 2024-07-31 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by danieleboaretti** [comment] 2024-08-01 06:19
Thank you Matt for your reply.

The `join` function from the collapse package is very fast and should do a good job.
https://sebkrantz.github.io/collapse/reference/join.html

I think that line could be replaced by this:
`.events <- join(.events, .ctl$iCov, on= .by, how="inner", multiple=TRUE)`

Those arguments should do the same thing as before.

It would be ideal to test this change and see if it actually helps. 

P.S. The collapse package is a very good package when dealing with data manipulation and aggregation, even more performant than data.table from what I have experienced. It might also help in other instances of rxode2.

Thank you very much!

**Comment by mattfidler** [comment] 2024-08-01 16:50
The `::join()` may help.  However, likely the best solution is to incorporate it into the `etTrans()` function (making sure the number of IDs in the input are the same).  Then no expensive merge would need to occur (though an expensive `order` or less expensive `data.table` `forder` would likely be needed).

**Comment by mattfidler** [comment] 2024-08-01 16:50
This may take a bit.

**Comment by mattfidler** [comment] 2024-08-01 23:40
The no merge branch really doesn't give much of a boost here:

``` r
library(collapse)
#> collapse 2.0.15, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
library(rxode2)
#> rxode2 2.1.3.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
library(magrittr)
nsub <- 100 # 100 sub-problems

mod1 <- rxode2({
    C2 = centr/V2
    C3 = peri/V3
    d/dt(depot) = -KA*depot
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3
    d/dt(peri) = Q*C2 - Q*C3
    d/dt(eff) = Kin - Kout*(1-C2/(EC50+C2))*eff
    eff(0) = 1
})
#> using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’


ev <- et() %>%
    et(amt=10000, addl=9,ii=12) %>%
    et(time=120, amt=20000, addl=4, ii=24) %>%
    et(0:240) ## Add Sampling

  sampling_times_df <- data.frame(
    id = rep(1:nsub, each = length(seq(0,240))),
    time = rep(seq(0,240), nsub),
    evid = 0,
    cmt = "(obs)"
  )

  ev %<>% rowbind(sampling_times_df, fill = TRUE)

  ev %<>% roworder(id, time, evid)

sigma <- matrix(c(0.09,0.08,0.08,0.25),2,2) # IIV covariance matrix
mv <- rxRmvn(n=nsub, rep(0,2), sigma) # Sample from covariance matrix
CL <- 7*exp(mv[,1])
V2 <- 40*exp(mv[,2])
params.all <- cbind(KA=0.3, CL=CL, V2=V2, Q=10, V3=300,
                    Kin=0.2, Kout=0.2, EC50=8)
params_df <- as.data.frame(params.all)
runiCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =params_df, events=ev)
}

icovs <- params_df[c("CL", "V2")]
params_small_icovs <- params_df[c("KA", "Q", "V3", "Kin", "Kout", "EC50")]
run_small_iCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =icovs, params = params_small_icovs, events=ev)
}
library(microbenchmark)
bench <- microbenchmark(run_small_iCov(), runiCov())
print(bench)
#> Unit: milliseconds
#>              expr      min        lq      mean    median       uq      max
#>  run_small_iCov()  61.9243  72.81749  90.93813  88.66759 101.1191 199.7552
#>         runiCov() 143.2548 169.69325 208.49916 200.53428 233.6643 380.7098
#>  neval
#>    100
#>    100
```

<sup>Created on 2024-08-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment] 2024-08-02 14:07
After taking care of some of the extras (like `keep` from `iCov`) this
is the timing of the branch I intend to merge:

``` r
library(collapse)
#> collapse 2.0.15, see ?`collapse-package` or ?`collapse-documentation`
#>
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#>
#>     D
library(rxode2)
#> rxode2 2.1.3.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
library(magrittr)
nsub <- 100 # 100 sub-problems

mod1 <- rxode2({
  C2 = centr/V2
  C3 = peri/V3
  d/dt(depot) = -KA*depot
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3
  d/dt(peri) = Q*C2 - Q*C3
  d/dt(eff) = Kin - Kout*(1-C2/(EC50+C2))*eff
  eff(0) = 1
})
#> using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’


ev <- et() %>%
  et(amt=10000, addl=9,ii=12) %>%
  et(time=120, amt=20000, addl=4, ii=24) %>%
  et(0:240) ## Add Sampling

sampling_times_df <- data.frame(
  id = rep(1:nsub, each = length(seq(0,240))),
  time = rep(seq(0,240), nsub),
  evid = 0,
  cmt = "(obs)"
)

ev %<>% rowbind(sampling_times_df, fill = TRUE)

ev %<>% roworder(id, time, evid)

sigma <- matrix(c(0.09,0.08,0.08,0.25),2,2) # IIV covariance matrix
mv <- rxRmvn(n=nsub, rep(0,2), sigma) # Sample from covariance matrix
CL <- 7*exp(mv[,1])
V2 <- 40*exp(mv[,2])
params.all <- cbind(KA=0.3, CL=CL, V2=V2, Q=10, V3=300,
                    Kin=0.2, Kout=0.2, EC50=8)
params_df <- as.data.frame(params.all)
runiCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =params_df, events=ev)
}

icovs <- params_df[c("CL", "V2")]
params_small_icovs <- params_df[c("KA", "Q", "V3", "Kin", "Kout", "EC50")]
run_small_iCov<- function(){
  # base::solve(mod1, params.all, ev, cores=6)[,c("sim.id", "time", "eff")]
  rxSolve(mod1, iCov =icovs, params = params_small_icovs, events=ev)
}
library(microbenchmark)
bench <- microbenchmark(run_small_iCov(), runiCov())
print(bench)
#> Unit: milliseconds
#>              expr      min       lq     mean   median       uq      max neval
#>  run_small_iCov() 39.36384 67.58382 85.96747 80.07564 105.2842 170.8217   100
#>         runiCov() 40.04360 71.08771 98.00756 95.62903 116.1400 245.3817   100

library(ggplot2)
autoplot(bench)
```

![](https://i.imgur.com/Z9XCJY4.png)

<sup>Created on 2024-08-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by danieleboaretti** [comment] 2024-08-02 15:05
It looks very good to me. The difference now is very small and I guess it might be just the extra time needed for adding the extra columns to the solved output in `runiCov`. Probably that can't be improved that much.
I hope it will see the light in a new release soon.

**Comment by mattfidler** [comment] 2024-08-02 16:20
Thanks.  Once the `::check()` is working I will merge the pull request (which will close this issue).

I hope to release later this year.

**Closed** 2024-08-02 18:04 UTC

**Comment by mattfidler** [comment] 2024-08-02 18:10
Since it was merged, you can try this out sooner by using `r-universe`.  If you are only using `rxode2` this will be the only package you would need to install.
